/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Test_Units;

import javax.swing.DefaultComboBoxModel;
import lab01_enrique.miranda_alvaro.cabrera_dilan.triana.*;

/**
 *
 * @author Enrique
 */
public class testeo extends javax.swing.JFrame {

    /**
     * Creates new form testeo
     */
    DefaultComboBoxModel search_atributes[];
    public testeo() {
        initComponents();
        search_atributes = new DefaultComboBoxModel[3];
        initAtributes();
        this.search_Property.setModel(search_atributes[search_Class.getSelectedIndex()]);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        search_Class = new javax.swing.JComboBox<>();
        search_Property = new javax.swing.JComboBox<>();
        searchBar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        consola = new javax.swing.JTextArea();
        search = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        search_Class.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuario", "Post", "Comentario" }));
        search_Class.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                search_ClassItemStateChanged(evt);
            }
        });

        search_Property.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        consola.setColumns(20);
        consola.setRows(5);
        jScrollPane1.setViewportView(consola);

        search.setText("Buscar");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(searchBar, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(search_Class, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(search_Property, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(search)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search_Class, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_Property, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void search_ClassItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_search_ClassItemStateChanged
        this.search_Property.setModel(search_atributes[search_Class.getSelectedIndex()]);
    }//GEN-LAST:event_search_ClassItemStateChanged

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        if(!searchBar.getText().isEmpty()){
            switch((String)search_Class.getSelectedItem()){
                case "Usuario":
                    break;
                case "Post":
                    break;
                case "Comentario":
                    break;
                        
            }
        }
    }//GEN-LAST:event_searchActionPerformed

    public void initAtributes(){
        this.search_atributes[0] = new DefaultComboBoxModel();
        this.search_atributes[0].addElement("id");
        this.search_atributes[0].addElement("name");
        this.search_atributes[0].addElement("username");
        this.search_atributes[0].addElement("email");
        this.search_atributes[0].addElement("dir-street");
        this.search_atributes[0].addElement("dir-suite");
        this.search_atributes[0].addElement("dir-city");
        this.search_atributes[0].addElement("dir-zipcode");
        this.search_atributes[0].addElement("geo-lat");
        this.search_atributes[0].addElement("geo-lng");
        this.search_atributes[0].addElement("phone");
        this.search_atributes[0].addElement("website");
        this.search_atributes[0].addElement("comp-name");
        this.search_atributes[0].addElement("comp-catchPhrase");
        this.search_atributes[0].addElement("comp-bs");
        this.search_atributes[1] = new DefaultComboBoxModel();
        this.search_atributes[1].addElement("userId");
        this.search_atributes[1].addElement("id");
        this.search_atributes[1].addElement("title");
        this.search_atributes[1].addElement("body");
        this.search_atributes[2] = new DefaultComboBoxModel();
        this.search_atributes[2].addElement("postId");
        this.search_atributes[2].addElement("id");
        this.search_atributes[2].addElement("name");
        this.search_atributes[2].addElement("email");
        this.search_atributes[2].addElement("body");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(testeo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(testeo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(testeo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(testeo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new testeo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea consola;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton search;
    private javax.swing.JTextField searchBar;
    private javax.swing.JComboBox<String> search_Class;
    private javax.swing.JComboBox<String> search_Property;
    // End of variables declaration//GEN-END:variables
}
